name: Deployment

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [angular, nest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ "${{ matrix.service }}" == "angular" ]; then
            cd frontend
          else
            cd backend
          fi
          npm install

      - name: Run tests
        run: |
          if [ "${{ matrix.service }}" == "angular" ]; then
            cd frontend
            npm test
          else
            cd backend
            npm run test
          fi

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        service: [angular, nest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ "${{ matrix.service }}" == "angular" ]; then
            cd frontend
          else
            cd backend
          fi
          npm install

      - name: Build project
        run: |
          if [ "${{ matrix.service }}" == "angular" ]; then
            cd frontend
            npm run build --prod
          else
            cd backend
            npm run build
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Angular to FTP
        if: matrix.service == 'angular'
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/FLYARTS-QUOTIDIAN/website/
          local-dir: frontend/dist/browser/

      - name: Deploy Nest.js to FTP
        if: matrix.service == 'nest'
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/FLYARTS-QUOTIDIAN/api/dist/
          local-dir: backend/dist/


